apiVersion: batch/v1
kind: Job
metadata:
  name: clima-pipeline-job
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: clima-pipeline
          image: clima-el-nino:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Never